on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: TESTS=all GOEXPERIMENT=loopvar go test -tags portable -timeout=1h -v -bench=. ./...
